name: deploy_prod
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Init deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      # - name: Install dependencies
      # run: npm install
      - name: Deploy API
        env:
          TEST: ${{ secrets.TEST }}
        # run: npx sst deploy api --stage=prod
        run: |
          echo $TEST
          echo tessssss
          echo $TEST
          echo tessssss
          echo tessssss
