name: deploy_prod
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Init deploy
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          SUB_DOMAIN: ${{ secrets.SUB_DOMAIN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Install dependencies
        run: npm install
      - name: Generate Prisma
        run: npx prisma generate
      - name: Deploy API
        run: npx sst deploy --stage=prod
